version: '3'

services:
  # blog:
  #   container_name: blog-app
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '9000:9000'
  #   volumes:
  #     - ./:/var/www/
  #   working_dir: /var/www/
  #   depends_on:
  #     - db
  #   networks:
  #     - laravel

  # nginx:
  #   container_name: blog-nginx
  #   image: nginx
  #   restart: unless-stopped    
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   volumes:
  #     - ./:/var/www
  #     - ./.docker/nginx/:/etc/nginx/conf.d/
  #   working_dir: /var/www/
  #   networks:
  #     - laravel

  mysql-db:
    image: mysql:5.7
    container_name: blog-mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_PASSWORD: laravel
    volumes:
        - ./.docker/mysql/dbdata:/var/lib/mysql      
    networks:
      - laravel

networks:
  laravel:
    driver: bridge